### ISSUE TITLE
Попробуй так)

### ISSUE THREAD

**Issue by JStormer** [makhinur/makhinur.github.io#1]
https://github.com/makhinur/makhinur.github.io/blob/df7de5e78e170bdb8fae2fa6edb7d9bc846a255f/src/router/index.js#L16
router.replace({ path: '/messages', redirect: '/' }) ?

**Comment by makhinur** [comment]
{
            path: '/messages',
            name: 'messages',
            redirect: '/',
            component: MainPage,
            props: (route) => { return route.query || {} }
        }
