### ISSUE TITLE
Можно изящней ;)

### ISSUE THREAD

**Issue by JStormer** [makhinur/makhinur.github.io#2]
https://github.com/makhinur/makhinur.github.io/blob/df7de5e78e170bdb8fae2fa6edb7d9bc846a255f/src/components/MainPage.vue#L30-L36

**Comment by makhinur** [comment]
добавила sort() в 49 строку во SearchBar.vue компонент:

           <v-btn
               text
                color="primary"
                @click="$refs.menu.save(searchDates);
                    $router.push({ name: 'messages', query: {date: searchDates.sort(), manager: searchManager}})"
            >
              OK
            </v-btn>
