### ISSUE TITLE
попробуй написать короче и проще

### ISSUE THREAD

**Issue by JStormer** [makhinur/makhinur.github.io#3]
https://github.com/makhinur/makhinur.github.io/blob/df7de5e78e170bdb8fae2fa6edb7d9bc846a255f/src/components/MainPage.vue#L37-L51

**Comment by makhinur** [comment]
watch: {

    '$route.query'() {
      let manager = this.$route.query.manager || [];
      let startDate = this.$route.query.date[0] || '2010-01-01';
      let endDate = this.$route.query.date[1] || '2030-12-31';

      this.filteredMessages = this.messages.filter(function (message) {
        return message.date >= startDate && message.date <= endDate && message.manager.includes(manager);
      })
    }
  }
